name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: bufbuild/buf-setup-action@v1
      with:
        version: "1.30.0"

    - uses: bufbuild/buf-lint-action@v1

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.4'

    - name: Build
      run: make build

    - name: Test
      run: make test
