name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-setup-action@v1
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.4'
          
      - name: Build Binary for Linux
        run: |
          make build
          zip "lda-linux-amd64.zip" "lda"

      - uses: actions/upload-artifact@v4
        with:
          name: lda-linux-amd64.zip
          path: lda-linux-amd64.zip

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-setup-action@v1

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.4'

      - name: Build Binary for macOS Intel
        run: |
          make build
          zip "lda-darwin-arm64.zip" "lda"

      - uses: actions/upload-artifact@v4
        with:
          name: lda-darwin-arm64.zip
          path: lda-darwin-arm64.zip

  create-release:
    needs: [build-linux, build-macos]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/lda-darwin-arm64.zip/lda-darwin-arm64.zip
            artifacts/lda-linux-amd64.zip/lda-linux-amd64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
